name: Deploy to VPS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, syrianzone]
    steps:
      - name: Sync and Deploy
        run: |
          git config --global --add safe.directory /home/syrian/public_html/repo
          cd /home/syrian/public_html/repo
          git fetch origin main
          git reset --hard origin/main
          chmod +x deploy.sh
          ./deploy.sh
